name: Cypress Cloud

on:
   workflow_dispatch:
      inputs:
         cli:
            description: Run by cypress
            default: node runner.js

jobs: 
  cypress-e2e-electron:
    runs-on: ubuntu-latest
    steps:
       - name: Get code
         uses: actions/checkout@v4.2.2

       - name: Cypress run
         uses: cypress-io/github-action@v6.5.0
         with: 
          install-command: yarn install
          browser: electron
          record: true
          group: UI Electron
          spec: cypress/e2e/*
         env:
          CYPRESS_RECORD_KEY: fbd3d92c-f1fa-44aa-b715-444fbe42023f
          GIT_HUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
