name: Cypress Cloud

on: [push]

jobs: 
  cypress-e2e-electron:
    runs-on: ubuntun-latest
    steps:
       - name: Get code
         uses: actions/checkout@v4.2.2

       - name: Cypress run
         uses: cypress-io/github-action@v6.5.0
         with: 
          install-command: yarn install
          browser: electron
          record: true
          group: UI Electron
          spec: cypress/e2e/*
         env:
          CYPRESS_RECORD_KEY: vvv
          GIT_HUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
