name: Cypress Tests

on:
   workflow_dispatch:
      inputs:
         cli:
            description: Run by cypress command line
            default: yarn cypress run

jobs:
   cypress-electron-tests:
     runs-on: ubuntun-latest
     steps:
       - name: Get code
         uses: actions/checkout@v4.2.2

       - name: install dependencies
         run: yarn cypress run

       - name: Run E2E tests
         run: yarn install
         
          
       
